version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:5001" 
    volumes:
      - ./backend:/app
    depends_on:
      - websocket

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./websocket:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
